### ISSUE TITLE
Traceback Problems

### ISSUE THREAD

**Issue by Avyansh0001** [byZeroOfficial/WebsiteGenerator#1]
Traceback (most recent call last):
  File "C:\Users\office1\Desktop\WebsiteGenerator-main\src\main.py", line 2, in <module>
    import asyncio
  File "C:\Users\office1\AppData\Local\Programs\Python\Python39\lib\asyncio\__init__.py", line 43, in <module>
    from .windows_events import *
  File "C:\Users\office1\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 17, in <module>
    from . import proactor_events
  File "C:\Users\office1\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 38, in <module>
    class _ProactorBasePipeTransport(transports._FlowControlMixin,
NameError: name 'transports' is not defined

#What shall I do? I have pip installed tho

**Comment by EinfachRuwen** [comment]
Hey 👋
You should try it again now. I removed the unnecessary import, so you can try it again. Tell me if it works now.

**Comment by EinfachRuwen** [comment]
Hey 👋🏻
Is this still a problem?

**Comment by Avyansh0001** [comment]
Hi 👋🏻 
Yes! now it is working
Sorry for the late reply 😢 

With royal regards,
`[Avyansh Ralph](avyanshralph.xyz)`
